use crate::ast::*;
use crate::lexer::Lexer;
use crate::token::Token;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum ParseError {
    #[error("lex error: {0}")]
    Lex(#[from] crate::lexer::LexError),
    #[error("unexpected token {found:?}, expected {expected}")]
    Unexpected { found: Token, expected: String },
    #[error("unexpected end of input")]
    Eof,
}

pub struct Parser {
    tokens: Vec<Token>,
    pos: usize,
    /// Synthetic recursive CTEs generated by variable-depth graph hops
    /// (`> label* >`) in the statement currently being parsed. Drained into
    /// the enclosing `SelectStmt.ctes` once that statement is done parsing.
    pending_ctes: Vec<CteDef>,
    cte_counter: usize,
}

pub fn parse_statements(src: &str) -> Result<Vec<Statement>, ParseError> {
    let tokens = Lexer::new(src).tokenize()?;
    let mut parser = Parser { tokens, pos: 0, pending_ctes: Vec::new(), cte_counter: 0 };
    let mut statements = Vec::new();
    loop {
        while parser.check(&Token::Semicolon) {
            parser.advance();
        }
        if parser.check(&Token::Eof) {
            break;
        }
        statements.push(parser.parse_statement()?);
        while parser.check(&Token::Semicolon) {
            parser.advance();
        }
    }
    Ok(statements)
}

impl Parser {
    fn peek(&self) -> &Token {
        self.tokens.get(self.pos).unwrap_or(&Token::Eof)
    }

    fn advance(&mut self) -> Token {
        let t = self.tokens.get(self.pos).cloned().unwrap_or(Token::Eof);
        if self.pos < self.tokens.len() {
            self.pos += 1;
        }
        t
    }

    fn check(&self, t: &Token) -> bool {
        self.peek() == t
    }

    fn eat(&mut self, t: &Token) -> bool {
        if self.check(t) {
            self.advance();
            true
        } else {
            false
        }
    }

    fn expect(&mut self, t: &Token, what: &str) -> Result<(), ParseError> {
        if self.eat(t) {
            Ok(())
        } else {
            Err(ParseError::Unexpected { found: self.peek().clone(), expected: what.to_string() })
        }
    }

    fn expect_ident(&mut self) -> Result<String, ParseError> {
        match self.advance() {
            Token::Ident(s) => Ok(s),
            other => Err(ParseError::Unexpected { found: other, expected: "identifier".to_string() }),
        }
    }

    fn parse_statement(&mut self) -> Result<Statement, ParseError> {
        match self.peek().clone() {
            Token::Select | Token::With => Ok(Statement::Select(self.parse_select()?)),
            Token::Insert => Ok(Statement::Insert(self.parse_insert()?)),
            Token::Update => Ok(Statement::Update(self.parse_update()?)),
            Token::Delete => Ok(Statement::Delete(self.parse_delete()?)),
            Token::Create => Ok(Statement::CreateTable(self.parse_create_table()?)),
            Token::Drop => self.parse_drop_table(),
            other => Err(ParseError::Unexpected { found: other, expected: "statement".to_string() }),
        }
    }

    // ---------- CREATE TABLE ----------

    fn parse_create_table(&mut self) -> Result<CreateTableStmt, ParseError> {
        self.expect(&Token::Create, "CREATE")?;
        self.expect(&Token::Table, "TABLE")?;
        let if_not_exists = if self.eat(&Token::If) {
            self.expect(&Token::Not, "NOT")?;
            self.expect(&Token::Exists, "EXISTS")?;
            true
        } else {
            false
        };
        let name = self.expect_ident()?;
        self.expect(&Token::LParen, "(")?;
        let mut columns = Vec::new();
        loop {
            columns.push(self.parse_column_def()?);
            if self.eat(&Token::Comma) {
                continue;
            }
            break;
        }
        self.expect(&Token::RParen, ")")?;
        Ok(CreateTableStmt { name, if_not_exists, columns })
    }

    fn parse_column_def(&mut self) -> Result<ColumnDef, ParseError> {
        let name = self.expect_ident()?;
        let data_type = match self.advance() {
            Token::TypeInteger => DataType::Integer,
            Token::TypeBigInt => DataType::BigInt,
            Token::TypeDouble => DataType::Double,
            Token::TypeText => DataType::Text,
            Token::TypeBoolean => DataType::Boolean,
            Token::TypeJson => DataType::Json,
            Token::TypeTimestamp => DataType::Timestamp,
            other => return Err(ParseError::Unexpected { found: other, expected: "column type".to_string() }),
        };
        let mut primary_key = false;
        let mut not_null = false;
        let mut default = None;
        loop {
            if self.eat(&Token::Primary) {
                self.expect(&Token::Key, "KEY")?;
                primary_key = true;
            } else if self.check(&Token::Not) {
                self.advance();
                self.expect(&Token::Null, "NULL")?;
                not_null = true;
            } else if self.eat(&Token::Default) {
                default = Some(self.parse_expr()?);
            } else {
                break;
            }
        }
        Ok(ColumnDef { name, data_type, primary_key, not_null, default })
    }

    fn parse_drop_table(&mut self) -> Result<Statement, ParseError> {
        self.expect(&Token::Drop, "DROP")?;
        self.expect(&Token::Table, "TABLE")?;
        let if_exists = if self.eat(&Token::If) {
            self.expect(&Token::Exists, "EXISTS")?;
            true
        } else {
            false
        };
        let name = self.expect_ident()?;
        Ok(Statement::DropTable { name, if_exists })
    }

    // ---------- INSERT ----------

    fn parse_insert(&mut self) -> Result<InsertStmt, ParseError> {
        self.expect(&Token::Insert, "INSERT")?;
        self.expect(&Token::Into, "INTO")?;
        let table = self.expect_ident()?;
        let columns = if self.eat(&Token::LParen) {
            let mut cols = Vec::new();
            loop {
                cols.push(self.expect_ident()?);
                if self.eat(&Token::Comma) {
                    continue;
                }
                break;
            }
            self.expect(&Token::RParen, ")")?;
            Some(cols)
        } else {
            None
        };
        self.expect(&Token::Values, "VALUES")?;
        let mut values = Vec::new();
        loop {
            self.expect(&Token::LParen, "(")?;
            let mut row = Vec::new();
            loop {
                row.push(self.parse_expr()?);
                if self.eat(&Token::Comma) {
                    continue;
                }
                break;
            }
            self.expect(&Token::RParen, ")")?;
            values.push(row);
            if self.eat(&Token::Comma) {
                continue;
            }
            break;
        }
        Ok(InsertStmt { table, columns, values })
    }

    // ---------- UPDATE ----------

    fn parse_update(&mut self) -> Result<UpdateStmt, ParseError> {
        self.expect(&Token::Update, "UPDATE")?;
        let table = self.expect_ident()?;
        self.expect(&Token::Set, "SET")?;
        let mut assignments = Vec::new();
        loop {
            let col = self.expect_ident()?;
            self.expect(&Token::Eq, "=")?;
            let val = self.parse_expr()?;
            assignments.push((col, val));
            if self.eat(&Token::Comma) {
                continue;
            }
            break;
        }
        let filter = if self.eat(&Token::Where) {
            Some(self.parse_expr()?)
        } else {
            None
        };
        Ok(UpdateStmt { table, assignments, filter })
    }

    // ---------- DELETE ----------

    fn parse_delete(&mut self) -> Result<DeleteStmt, ParseError> {
        self.expect(&Token::Delete, "DELETE")?;
        self.expect(&Token::From, "FROM")?;
        let table = self.expect_ident()?;
        let filter = if self.eat(&Token::Where) {
            Some(self.parse_expr()?)
        } else {
            None
        };
        Ok(DeleteStmt { table, filter })
    }

    // ---------- SELECT ----------

    fn parse_select(&mut self) -> Result<SelectStmt, ParseError> {
        let mut ctes = Vec::new();
        if self.eat(&Token::With) {
            let recursive = self.eat(&Token::Recursive);
            loop {
                let name = self.expect_ident()?;
                let columns = if self.eat(&Token::LParen) {
                    let mut cols = Vec::new();
                    loop {
                        cols.push(self.expect_ident()?);
                        if self.eat(&Token::Comma) {
                            continue;
                        }
                        break;
                    }
                    self.expect(&Token::RParen, ")")?;
                    Some(cols)
                } else {
                    None
                };
                self.expect(&Token::As, "AS")?;
                self.expect(&Token::LParen, "(")?;
                let query = self.parse_set_expr()?;
                self.expect(&Token::RParen, ")")?;
                ctes.push(CteDef { name, columns, recursive, query: Box::new(query) });
                if self.eat(&Token::Comma) {
                    continue;
                }
                break;
            }
        }

        let body = self.parse_set_expr()?;
        ctes.extend(std::mem::take(&mut self.pending_ctes));

        let mut order_by = Vec::new();
        if self.eat(&Token::Order) {
            self.expect(&Token::By, "BY")?;
            loop {
                let expr = self.parse_expr()?;
                let desc = if self.eat(&Token::Desc) {
                    true
                } else {
                    self.eat(&Token::Asc);
                    false
                };
                order_by.push(OrderByItem { expr, desc });
                if self.eat(&Token::Comma) {
                    continue;
                }
                break;
            }
        }

        let limit = if self.eat(&Token::Limit) {
            Some(self.parse_int_literal()?)
        } else {
            None
        };
        let offset = if self.eat(&Token::Offset) {
            Some(self.parse_int_literal()?)
        } else {
            None
        };

        Ok(SelectStmt { ctes, body, order_by, limit, offset })
    }

    fn parse_int_literal(&mut self) -> Result<i64, ParseError> {
        match self.advance() {
            Token::Number(s) => s.parse::<i64>().map_err(|_| ParseError::Unexpected {
                found: Token::Number(s),
                expected: "integer".to_string(),
            }),
            other => Err(ParseError::Unexpected { found: other, expected: "integer".to_string() }),
        }
    }

    fn parse_set_expr(&mut self) -> Result<SetExpr, ParseError> {
        let mut left = SetExpr::Select(Box::new(self.parse_select_core()?));
        loop {
            if self.eat(&Token::Union) {
                let all = self.eat(&Token::All);
                let right = SetExpr::Select(Box::new(self.parse_select_core()?));
                left = SetExpr::Union { left: Box::new(left), all, right: Box::new(right) };
            } else {
                break;
            }
        }
        Ok(left)
    }

    fn parse_select_core(&mut self) -> Result<SelectCore, ParseError> {
        self.expect(&Token::Select, "SELECT")?;
        let distinct = self.eat(&Token::Distinct);

        let mut projection = Vec::new();
        loop {
            if self.check(&Token::Star) {
                self.advance();
                projection.push(SelectItem::Wildcard);
            } else {
                let expr = self.parse_expr()?;
                let alias = if self.eat(&Token::As) {
                    Some(self.expect_ident()?)
                } else if let Token::Ident(name) = self.peek().clone() {
                    // implicit alias: `expr name`
                    self.advance();
                    Some(name)
                } else {
                    None
                };
                projection.push(SelectItem::Expr { expr, alias });
            }
            if self.eat(&Token::Comma) {
                continue;
            }
            break;
        }

        let from = if self.eat(&Token::From) {
            Some(self.parse_table_ref()?)
        } else {
            None
        };

        let mut joins = Vec::new();
        if let Some(first) = &from {
            joins.extend(self.parse_graph_hops(table_alias(first))?);
        }
        loop {
            let kind = if self.eat(&Token::Inner) {
                self.expect(&Token::Join, "JOIN")?;
                JoinKind::Inner
            } else if self.eat(&Token::Left) {
                self.eat(&Token::Outer);
                self.expect(&Token::Join, "JOIN")?;
                JoinKind::Left
            } else if self.eat(&Token::Join) {
                JoinKind::Inner
            } else {
                break;
            };
            let table = self.parse_table_ref()?;
            self.expect(&Token::On, "ON")?;
            let on = self.parse_expr()?;
            joins.push(JoinClause { kind, table, on });
        }

        let filter = if self.eat(&Token::Where) {
            Some(self.parse_expr()?)
        } else {
            None
        };

        let mut group_by = Vec::new();
        if self.eat(&Token::Group) {
            self.expect(&Token::By, "BY")?;
            loop {
                group_by.push(self.parse_expr()?);
                if self.eat(&Token::Comma) {
                    continue;
                }
                break;
            }
        }

        let having = if self.eat(&Token::Having) {
            Some(self.parse_expr()?)
        } else {
            None
        };

        Ok(SelectCore { distinct, projection, from, joins, filter, group_by, having })
    }

    fn parse_table_ref(&mut self) -> Result<TableRef, ParseError> {
        let name = self.expect_ident()?;
        let alias = if self.eat(&Token::As) {
            Some(self.expect_ident()?)
        } else if let Token::Ident(a) = self.peek().clone() {
            self.advance();
            Some(a)
        } else {
            None
        };
        Ok(TableRef { name, alias })
    }

    /// Graph-traversal sugar: `left > label > right [> label2 > right2 ...]`
    /// desugars to joins against a generic `edges(from_id, to_id, label)` table:
    /// `JOIN edges __eN ON __eN.from_id = left.id AND __eN.label = 'label'
    ///  JOIN right ON right.id = __eN.to_id`.
    ///
    /// `> label* >` (star after the label) means "one or more hops labeled
    /// `label`" instead of exactly one hop: it desugars to a synthetic
    /// `WITH RECURSIVE` transitive closure over `edges`, joined on start/end
    /// id, so it can find targets at any depth.
    fn parse_graph_hops(&mut self, start_alias: String) -> Result<Vec<JoinClause>, ParseError> {
        let mut joins = Vec::new();
        let mut left_alias = start_alias;
        let mut hop = 0usize;
        while self.eat(&Token::Gt) {
            let label = self.expect_ident()?;
            let variable_depth = self.eat(&Token::Star);
            self.expect(&Token::Gt, ">")?;
            let target = self.parse_table_ref()?;
            let target_alias = table_alias(&target);
            hop += 1;

            if variable_depth {
                let cte_name = format!("__reach{}", self.cte_counter);
                self.cte_counter += 1;
                self.pending_ctes.push(reachability_cte(&cte_name, &label));

                let path_alias = format!("__path{hop}");
                joins.push(JoinClause {
                    kind: JoinKind::Inner,
                    table: TableRef { name: cte_name, alias: Some(path_alias.clone()) },
                    on: Expr::BinaryOp {
                        left: Box::new(col(&path_alias, "start_id")),
                        op: BinOp::Eq,
                        right: Box::new(col(&left_alias, "id")),
                    },
                });
                joins.push(JoinClause {
                    kind: JoinKind::Inner,
                    table: target,
                    on: Expr::BinaryOp {
                        left: Box::new(col(&target_alias, "id")),
                        op: BinOp::Eq,
                        right: Box::new(col(&path_alias, "id")),
                    },
                });
            } else {
                let edge_alias = format!("__edge{hop}");
                joins.push(JoinClause {
                    kind: JoinKind::Inner,
                    table: TableRef { name: "edges".to_string(), alias: Some(edge_alias.clone()) },
                    on: Expr::BinaryOp {
                        left: Box::new(Expr::BinaryOp {
                            left: Box::new(col(&edge_alias, "from_id")),
                            op: BinOp::Eq,
                            right: Box::new(col(&left_alias, "id")),
                        }),
                        op: BinOp::And,
                        right: Box::new(Expr::BinaryOp {
                            left: Box::new(col(&edge_alias, "label")),
                            op: BinOp::Eq,
                            right: Box::new(Expr::Literal(Literal::Text(label))),
                        }),
                    },
                });
                joins.push(JoinClause {
                    kind: JoinKind::Inner,
                    table: target,
                    on: Expr::BinaryOp {
                        left: Box::new(col(&target_alias, "id")),
                        op: BinOp::Eq,
                        right: Box::new(col(&edge_alias, "to_id")),
                    },
                });
            }

            left_alias = target_alias;
        }
        Ok(joins)
    }

    // ---------- Expressions (Pratt parser) ----------

    fn parse_expr(&mut self) -> Result<Expr, ParseError> {
        self.parse_or()
    }

    fn parse_or(&mut self) -> Result<Expr, ParseError> {
        let mut left = self.parse_and()?;
        while self.eat(&Token::Or) {
            let right = self.parse_and()?;
            left = Expr::BinaryOp { left: Box::new(left), op: BinOp::Or, right: Box::new(right) };
        }
        Ok(left)
    }

    fn parse_and(&mut self) -> Result<Expr, ParseError> {
        let mut left = self.parse_not()?;
        while self.eat(&Token::And) {
            let right = self.parse_not()?;
            left = Expr::BinaryOp { left: Box::new(left), op: BinOp::And, right: Box::new(right) };
        }
        Ok(left)
    }

    fn parse_not(&mut self) -> Result<Expr, ParseError> {
        if self.eat(&Token::Not) {
            let expr = self.parse_not()?;
            Ok(Expr::UnaryOp { op: UnOp::Not, expr: Box::new(expr) })
        } else {
            self.parse_comparison()
        }
    }

    fn parse_comparison(&mut self) -> Result<Expr, ParseError> {
        let expr = self.parse_concat()?;

        if self.eat(&Token::Is) {
            let negated = self.eat(&Token::Not);
            self.expect(&Token::Null, "NULL")?;
            return Ok(Expr::IsNull { expr: Box::new(expr), negated });
        }

        let negated = self.eat(&Token::Not);
        if self.eat(&Token::In) {
            self.expect(&Token::LParen, "(")?;
            let mut list = Vec::new();
            if !self.check(&Token::RParen) {
                loop {
                    list.push(self.parse_expr()?);
                    if self.eat(&Token::Comma) {
                        continue;
                    }
                    break;
                }
            }
            self.expect(&Token::RParen, ")")?;
            return Ok(Expr::InList { expr: Box::new(expr), list, negated });
        }
        if self.eat(&Token::Between) {
            let low = self.parse_concat()?;
            self.expect(&Token::And, "AND")?;
            let high = self.parse_concat()?;
            return Ok(Expr::Between { expr: Box::new(expr), low: Box::new(low), high: Box::new(high), negated });
        }
        if negated {
            // NOT was consumed speculatively but no IN/BETWEEN followed; treat as NOT (expr = ...)
            // Only LIKE is valid here besides IN/BETWEEN.
            if self.eat(&Token::Like) {
                let pattern = self.parse_concat()?;
                let like = Expr::BinaryOp { left: Box::new(expr), op: BinOp::Like, right: Box::new(pattern) };
                return Ok(Expr::UnaryOp { op: UnOp::Not, expr: Box::new(like) });
            }
            return Err(ParseError::Unexpected { found: self.peek().clone(), expected: "IN, BETWEEN or LIKE after NOT".to_string() });
        }

        if self.eat(&Token::Like) {
            let pattern = self.parse_concat()?;
            return Ok(Expr::BinaryOp { left: Box::new(expr), op: BinOp::Like, right: Box::new(pattern) });
        }

        let op = match self.peek() {
            Token::Eq => Some(BinOp::Eq),
            Token::NotEq => Some(BinOp::NotEq),
            Token::Lt => Some(BinOp::Lt),
            Token::LtEq => Some(BinOp::LtEq),
            Token::Gt => Some(BinOp::Gt),
            Token::GtEq => Some(BinOp::GtEq),
            _ => None,
        };
        if let Some(op) = op {
            self.advance();
            let right = self.parse_concat()?;
            return Ok(Expr::BinaryOp { left: Box::new(expr), op, right: Box::new(right) });
        }

        Ok(expr)
    }

    fn parse_concat(&mut self) -> Result<Expr, ParseError> {
        let mut left = self.parse_additive()?;
        loop {
            let op = match self.peek() {
                Token::Concat => BinOp::Concat,
                Token::Arrow => BinOp::JsonGet,
                Token::ArrowText => BinOp::JsonGetText,
                _ => break,
            };
            self.advance();
            let right = self.parse_additive()?;
            left = Expr::BinaryOp { left: Box::new(left), op, right: Box::new(right) };
        }
        Ok(left)
    }

    fn parse_additive(&mut self) -> Result<Expr, ParseError> {
        let mut left = self.parse_multiplicative()?;
        loop {
            let op = match self.peek() {
                Token::Plus => BinOp::Add,
                Token::Minus => BinOp::Sub,
                _ => break,
            };
            self.advance();
            let right = self.parse_multiplicative()?;
            left = Expr::BinaryOp { left: Box::new(left), op, right: Box::new(right) };
        }
        Ok(left)
    }

    fn parse_multiplicative(&mut self) -> Result<Expr, ParseError> {
        let mut left = self.parse_unary()?;
        loop {
            let op = match self.peek() {
                Token::Star => BinOp::Mul,
                Token::Slash => BinOp::Div,
                Token::Percent => BinOp::Mod,
                _ => break,
            };
            self.advance();
            let right = self.parse_unary()?;
            left = Expr::BinaryOp { left: Box::new(left), op, right: Box::new(right) };
        }
        Ok(left)
    }

    fn parse_unary(&mut self) -> Result<Expr, ParseError> {
        if self.eat(&Token::Minus) {
            let expr = self.parse_unary()?;
            return Ok(Expr::UnaryOp { op: UnOp::Neg, expr: Box::new(expr) });
        }
        self.parse_primary()
    }

    fn parse_primary(&mut self) -> Result<Expr, ParseError> {
        match self.peek().clone() {
            Token::Number(s) => {
                self.advance();
                if s.contains('.') || s.contains('e') || s.contains('E') {
                    Ok(Expr::Literal(Literal::Float(s.parse().unwrap())))
                } else {
                    Ok(Expr::Literal(Literal::Int(s.parse().unwrap())))
                }
            }
            Token::String(s) => {
                self.advance();
                Ok(Expr::Literal(Literal::Text(s)))
            }
            Token::Null => {
                self.advance();
                Ok(Expr::Literal(Literal::Null))
            }
            Token::True => {
                self.advance();
                Ok(Expr::Literal(Literal::Bool(true)))
            }
            Token::False => {
                self.advance();
                Ok(Expr::Literal(Literal::Bool(false)))
            }
            Token::Star => {
                // Only valid inside COUNT(*), handled by caller; treat bare * as error otherwise.
                self.advance();
                Ok(Expr::CountStar)
            }
            Token::LParen => {
                self.advance();
                let expr = self.parse_expr()?;
                self.expect(&Token::RParen, ")")?;
                Ok(expr)
            }
            Token::Ident(name) => {
                self.advance();
                if self.eat(&Token::LParen) {
                    // function call
                    let mut args = Vec::new();
                    if self.check(&Token::Star) {
                        self.advance();
                        args.push(Expr::CountStar);
                    } else if !self.check(&Token::RParen) {
                        loop {
                            args.push(self.parse_expr()?);
                            if self.eat(&Token::Comma) {
                                continue;
                            }
                            break;
                        }
                    }
                    self.expect(&Token::RParen, ")")?;
                    return Ok(Expr::FunctionCall { name, args });
                }
                if self.eat(&Token::Dot) {
                    let col = self.expect_ident()?;
                    return Ok(Expr::Column(ColumnRef { table: Some(name), name: col }));
                }
                Ok(Expr::Column(ColumnRef { table: None, name }))
            }
            other => Err(ParseError::Unexpected { found: other, expected: "expression".to_string() }),
        }
    }
}

fn table_alias(t: &TableRef) -> String {
    t.alias.clone().unwrap_or_else(|| t.name.clone())
}

fn col(table: &str, name: &str) -> Expr {
    Expr::Column(ColumnRef { table: Some(table.to_string()), name: name.to_string() })
}

fn eq(left: Expr, right: Expr) -> Expr {
    Expr::BinaryOp { left: Box::new(left), op: BinOp::Eq, right: Box::new(right) }
}

/// Builds the `WITH RECURSIVE <name>(start_id, id) AS (...)` transitive
/// closure of `edges` rows labeled `label`, used by variable-depth graph
/// hops (`> label* >`). Row `(start_id, id)` means `id` is reachable from
/// `start_id` via one or more `label` edges.
fn reachability_cte(name: &str, label: &str) -> CteDef {
    let label_filter = |edge_alias: &str| eq(col(edge_alias, "label"), Expr::Literal(Literal::Text(label.to_string())));

    let base = SelectCore {
        distinct: false,
        projection: vec![
            SelectItem::Expr { expr: col("edges", "from_id"), alias: Some("start_id".to_string()) },
            SelectItem::Expr { expr: col("edges", "to_id"), alias: Some("id".to_string()) },
        ],
        from: Some(TableRef { name: "edges".to_string(), alias: None }),
        joins: vec![],
        filter: Some(label_filter("edges")),
        group_by: vec![],
        having: None,
    };

    let step = SelectCore {
        distinct: false,
        projection: vec![
            SelectItem::Expr { expr: col("r", "start_id"), alias: Some("start_id".to_string()) },
            SelectItem::Expr { expr: col("e", "to_id"), alias: Some("id".to_string()) },
        ],
        from: Some(TableRef { name: name.to_string(), alias: Some("r".to_string()) }),
        joins: vec![JoinClause {
            kind: JoinKind::Inner,
            table: TableRef { name: "edges".to_string(), alias: Some("e".to_string()) },
            on: Expr::BinaryOp {
                left: Box::new(eq(col("e", "from_id"), col("r", "id"))),
                op: BinOp::And,
                right: Box::new(label_filter("e")),
            },
        }],
        filter: None,
        group_by: vec![],
        having: None,
    };

    CteDef {
        name: name.to_string(),
        columns: None,
        recursive: true,
        // Plain UNION (not ALL): dedupes (start_id, id) pairs so cyclic
        // graphs terminate instead of re-expanding the same reachable pair
        // through ever-longer paths forever.
        query: Box::new(SetExpr::Union {
            left: Box::new(SetExpr::Select(Box::new(base))),
            all: false,
            right: Box::new(SetExpr::Select(Box::new(step))),
        }),
    }
}
